import type { Metadata } from "next";

import './globals.css'
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: "Trek Mate",
  description: "Generated by create next appA modern camping-focused travel application featuring responsive design and optimized for seamless UI/UX interactions, built with Tailwind CSS and Next.js.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="relative overflow-hidden">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  )
}